version: "3.9"

services:
  server:
    image: bingo/prod
    container_name: server
    restart: always
    build: .
    ports:
      - 8081:8081
    links:
      - "db:database"
    command: /app -db=172.25.0.2:28015

  db:
    container_name: rethinkdb
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ./data:/data

  test:
    image: bingo/dev
    container_name: test
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/app
    command: make test

  lint:
    image: bingo/dev
    container_name: test
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/app
    command: make lint
