version: "3.9"

services:
  server:
    image: bingo/prod
    container_name: server
    build: .
    ports:
      - 8081:8081

  db:
    container_name: rethinkdb
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ./data:/data

  test:
    image: bingo/dev
    container_name: test
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/app
    command: bash -c 'go test ./... -count=1 -cover | grep -v ?'

  lint:
    image: bingo/dev
    container_name: test
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/app
    command: golangci-lint run --timeout=5m
