version: "3.9"

services:
  server:
    container_name: server
    build: .
    ports:
      - 8081:8081

  db:
    container_name: rethinkdb
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - ./data:/data

  test:
    container_name: test
    build:
      context: .
      target: build
    volumes:
      - ./:/go/src/app
    command: bash -c 'go test ./... -count=1 -cover | grep -v ?'
